// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiciosGenerales.Infraestructura.Data;

#nullable disable

namespace ServiciosGenerales.Infraestructura.Migrations
{
    [DbContext(typeof(UniversidadDbContext))]
    partial class UniversidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReemplazadoPor")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_Fechas", "[FechaExpiracion] > [FechaCreacion] AND ([FechaRevocacion] IS NULL OR [FechaRevocacion] >= [FechaCreacion])");
                        });
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RegistroParqueo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PuertaAcceso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RegistradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaSalida")
                        .HasFilter("[FechaSalida] IS NULL");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistrosParqueo", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosParqueo_Fechas", "[FechaSalida] IS NULL OR [FechaSalida] >= [FechaIngreso]");
                        });
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RegistroPorteria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaDestino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MotivoVisita")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PuertaEntrada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PuertaSalida")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RegistradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaSalida")
                        .HasFilter("[FechaSalida] IS NULL");

                    b.HasIndex("RegistradoPorUsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RegistrosPorteria", null, t =>
                        {
                            t.HasCheckConstraint("CK_RegistrosPorteria_Fechas", "[FechaSalida] IS NULL OR [FechaSalida] >= [FechaEntrada]");
                        });
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "PorteroParqueo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "PorteroPorteria"
                        });
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.TiposUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposUsuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Estudiante"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Trabajador"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Visitante"
                        });
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BloqueoHasta")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoIdentidad")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RefreshToken", b =>
                {
                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RegistroParqueo", b =>
                {
                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Vehiculo", "Vehiculo")
                        .WithMany("RegistrosParqueo")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistradoPor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.RegistroPorteria", b =>
                {
                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("RegistrosPorteria")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistradoPor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Usuario", b =>
                {
                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiciosGenerales.Dominio.Entidades.TiposUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("ServiciosGenerales.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Vehiculos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.TiposUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("RegistrosPorteria");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("ServiciosGenerales.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Navigation("RegistrosParqueo");
                });
#pragma warning restore 612, 618
        }
    }
}
